catalog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import profile_view, CustomPasswordChangeView
urlpatterns = [
    path('', views.index, name='index'),  # Главная страница каталога
    path('homes/', views.HomeListView.as_view(), name='homes'),
    path('landlords/', views.LandlordListView.as_view(), name='landlords'),
    path('landlord/<int:pk>/', views.LandlordDetailView.as_view(), name='landlord-detail'),
    path('home/<uuid:pk>/', views.HomeDetailView.as_view(), name='home-detail'),

    # Аутентификация
    path('login/', auth_views.LoginView.as_view(template_name='catalog/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Профиль
    path('register/', views.register, name='register'),
    path('profile/', profile_view, name='profile'),
    path('profile/change-password/', CustomPasswordChangeView.as_view(), name='change_password'),

    # Объявления
    path('create-home/', views.create_home, name='home_form'),
]

homehunt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from catalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')), # переадресация с корневого url на /catalog
    path("__reload__/", include("django_browser_reload.urls")),  # Маршруты для django-browser-reload
]


# URLs
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # добавляем статические(css,js,)

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify

class CustomUser(AbstractUser):
    phone_number = models.CharField(max_length=15, blank=True, null=True)

from django.contrib.auth import get_user_model
User = get_user_model()

class QuantityRooms(models.Model):
    """
    Модель для ввода количества комнат в квартире (например, студия, однокомнатная, двухкомнатная и т. д.).
    """
    name = models.CharField(
        max_length=200,
        help_text="Введите количество комнат (например, студия, однокомнатная, двухкомнатная и т. д.)."
    )

    def __str__(self):
        return self.name

class HomeImage(models.Model):
    home = models.ForeignKey('Home', on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='home_images/', help_text="Загрузите изображение квартиры")

class Home(models.Model):
    """
    Модель, представляющая квартиру (но не конкретный экземпляр квартиры).
    """
    title = models.CharField(
        max_length=200,
        help_text="Краткое описание квартиры"
    )
    landlord = models.ForeignKey(
        'Landlord',
        on_delete=models.SET_NULL,
        null=True,
        help_text="Арендодатель квартиры"
    )
    description = models.TextField(
        max_length=1000,
        help_text="Введите описание квартиры"
    )
    price = models.CharField(
        max_length=10,
        help_text="Цена аренды"
    )
    quantity = models.ForeignKey(
        'QuantityRooms',
        on_delete=models.SET_NULL,
        null=True,
        help_text="Выберите количество комнат"
    )
    # Адрес квартиры
    city = models.CharField(
        max_length=100,
        help_text="Город, где находится квартира"
    )
    street = models.CharField(
        max_length=200,
        help_text="Улица, где находится квартира"
    )
    house_number = models.CharField(
        max_length=10,
        help_text="Номер дома"
    )
    apartment_number = models.CharField(
        max_length=10,
        help_text="Номер квартиры",
        blank=True
    )
    # Уникальный URL квартиры
    original_address = models.URLField(
        unique=True,
        blank = True,
        null=True,
        help_text="Уникальный URL с оригинального сайта"
    )
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="Уникальный ID квартиры"
    )
    # Счётчик просмотров
    views_count = models.IntegerField(
        default=0
    )
    publication_date = models.DateTimeField(
        auto_now_add=True
    )
    adrs = models.CharField(
        max_length=100,
        help_text="Адрес из объявления",
        blank=True
    )

    class Meta:
        ordering = ["city", "street", "house_number", "price"]

    def __str__(self):
        return f"{self.title} - {self.city}, {self.street}, {self.house_number}, {self.price}"

    def get_absolute_url(self):
        """
        Возвращает URL для доступа к конкретной квартире.
        """
        return reverse('home-detail', args=[str(self.id)])



class Landlord(models.Model):
    """
    Модель представляющая арендодателя
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="landlord", null=True, blank=True)
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=100)

    def get_absolute_url(self):
        """
         Возвращает URL-адрес для доступа к конкретному экземпляру арендодателя.
        """
        return reverse('landlord-detail', args=[str(self.id)])

    def __str__(self):
        return f"{self.name}, {self.phone_number}"

catalog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from catalog.models import Home, HomeImage

CustomUser = get_user_model()
class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField()
    phone_number = forms.CharField(required=False)
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'phone_number', 'password1', 'password2']

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if CustomUser.objects.filter(phone_number=phone_number).exists():
            raise forms.ValidationError("This phone number is already in use.")
        return phone_number

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if CustomUser.objects.filter(email=email).exists(): 
            raise forms.ValidationError("Email is already in use.")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match.")
        return password2

class HomeForm(forms.ModelForm):
    class Meta:
        model = Home
        fields = ['title', 'description', 'price', 'quantity', 'city', 'street', 'house_number', 'apartment_number']

        def __init__(self, *args, user=None, **kwargs):
            super().__init__(*args, **kwargs)


class HomeImageForm(forms.ModelForm):
    class Meta:
        model = HomeImage
        fields = ['image']

catalog/views.py
from .models import Home, Landlord, QuantityRooms, HomeImage
from django.views import generic
from django.contrib.auth import login
from .forms import HomeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from .forms import CustomUserCreationForm

# Create your views here.

def index(request):
    """
    Домашняя страница
    """

    num_homes = Home.objects.all().count()
    num_landlords = Landlord.objects.all().count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    # Render the HTML template index.html with the data in the context variable.
    return render(
        request,
        'index.html',
        context={'num_homes': num_homes, 'num_landlords': num_landlords, 'num_visits': num_visits}
    )

@login_required
def profile_view(request):
    return render(request, 'catalog/profile.html')

class CustomPasswordChangeView(PasswordChangeView):
    form_class = PasswordChangeForm
    template_name = 'catalog/change_password.html'
    success_url = reverse_lazy('profile')

    def form_valid(self, form):
        messages.success(self.request, "Your password was successfully updated!")
        return super().form_valid(form)

def register(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)  # Автоматически логиним пользователя
            return redirect('index')  # Редирект на главную
    else:
        form = CustomUserCreationForm()
    return render(request, 'catalog/register.html', {'form': form})

@login_required
def create_home(request):
    if request.method == "POST":
        form = HomeForm(request.POST, request.FILES)
        files = request.FILES.getlist('images')
        if form.is_valid():
            home = form.save(commit=False)

            landlord, created = Landlord.objects.get_or_create(
                user=request.user,
                defaults={
                    "name": request.user.username,
                    "phone_number": request.user.phone_number or "Не указан",
                }
            )

            home.landlord = landlord
            home.save()
            for file in files:
                HomeImage.objects.create(home=home, image=file)
            return redirect("home-detail", pk=home.pk)
    else:
            form = HomeForm()
    return render(request, 'catalog/home_form.html', {'form': form})


class HomeListView(generic.ListView):
    model = Home
    template_name = 'catalog/home_list.html'  # Укажите путь к шаблону
    context_object_name = 'home_list'  # Имя переменной контекста для шаблона
    paginate_by = 50  # Опционально: количество элементов на странице

class HomeDetailView(generic.DetailView):
    model = Home
    template_name = 'catalog/home_detail.html'  # Укажите путь к вашему шаблону
    context_object_name = 'home'  # Опционально: имя переменной контекста

    def home_detail(request, pk):
        home = get_object_or_404(Home, pk=pk)
        return render(request, 'catalog/home_detail.html', {'home': home})

    def get_object(self, queryset=None):
        home = super().get_object(queryset)

        # Проверяем, был ли пользователь уже на этой странице
        session_key = f'viewed_home_{home.id}'
        if not self.request.session.get(session_key, False):
            home.views_count += 1
            home.save(update_fields=['views_count'])
            self.request.session[session_key] = True  # Помечаем, что он уже смотрел

        return home

class LandlordListView(generic.ListView):
    model = Landlord
    template_name = 'catalog/landlord_list.html'  # Укажите путь к шаблону
    context_object_name = 'landlords'  # Имя переменной контекста для шаблона

class LandlordDetailView(generic.DetailView):
    model = Landlord
    template_name = 'catalog/landlord_detail.html'

catalog/templates/catalog/change_password.html
{% extends "base_generic.html" %}

{% block content %}
  <h2>Change Password</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change</button>
  </form>
{% endblock %}

catalog/templates/catalog/home_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ home.title }}</h1>

  <p><strong>Landlord:</strong>
    <a href="{{ home.landlord.get_absolute_url }}">{{ home.landlord.name }}</a>
    (Phone: {{ home.landlord.phone_number }})
  </p>

    <h3>Images:</h3>
  {% if home.images.all %}
    <div class="row">
      {% for image in home.images.all %}
        <div class="col-md-4">
          <img src="{{ image.image.url }}" class="img-fluid rounded" alt="Image of {{ home.title }}">
        </div>
      {% endfor %}
    </div>
  {% else %}
    <p>No images available for this home.</p>
  {% endif %}

  <p><strong>Price:</strong> {{ home.price }} руб.</p>
  <p><strong>Rooms:</strong> {{ home.quantity }}</p>

      <h3>Address:</h3>
  <p>{{ home.city }}, {{ home.street }} {{ home.house_number }}{% if home.apartment_number %},Apt {{ home.apartment_number }}{% endif %}</p>

  <p><strong>Description:</strong> {{ home.description }}</p>

    {% if home.original_address %}
    <p><strong>Для уточнения более детальной информации, вы можете перейти по ссылке:</strong>
        <a href="{{ home.original_address }}" target="_blank">View Source</a>
  {% endif %}

    <p><strong>Просмотров:</strong> {{ home.views_count }}</p>
    <p>Дата добавления: {{ home.publication_date|date:"d E Y H:i" }}</p>
{% endblock %}

catalog/templates/catalog/home_form.html
{% extends "base_generic.html" %}

{% block content %}
  <h2>Add New Home Listing</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

      <label for="id_images">Add images:</label>
      <input type="file" name="images" id="id_images" multiple>

    <button type="submit">Create</button>
  </form>
{% endblock %}

catalog/templates/catalog/home_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Home List</h1>

    {% if home_list %}
    <ul>

      {% for home in home_list %}
      <li>
       {% if home.images.all %}
         <div class="row">
             {% for image in home.images.all %}
                 <div class="col-md-4">
                     <img src="{{ image.image.url }}" class="img-fluid" alt="Image of {{ home.title }}">
                 </div>
             {% endfor %}
         </div>
       {% endif %}

        <a href="{{ home.get_absolute_url }}">{{ home.title }}</a> ({{home.landlord}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no home in the city.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/landlord_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ landlord.name }}</h1>
  <p><strong>Name:</strong> {{ landlord.name }}</p>
  <p><strong>Phone:</strong> {{ landlord.phone_number }}</p>

  <h2>Homes for Rent</h2>
  {% if landlord.home_set.all %}
    <ul>
      {% for home in landlord.home_set.all %}
        <li>
          <a href="{{ home.get_absolute_url }}">{{ home.title }}</a> - {{ home.price }}$
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No homes available for rent.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/landlord_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Landlords</h1>
  <ul>
    {% for landlord in landlords %}
      <li>
        <a href="{{ landlord.get_absolute_url }}">{{ landlord.name }}</a> - {{ landlord.phone_number }}
      </li>
    {% endfor %}
  </ul>
{% endblock %}

catalog/templates/catalog/login.html
{% extends "base_generic.html" %}

{% block content %}
  <h2>Login</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Log In</button>
  </form>
  <p>Don't have an account? <a href="{% url 'register' %}">Register here</a></p>
{% endblock %}

catalog/templates/catalog/profile.html
{% extends "base_generic.html" %}

{% block content %}
  <h2>Profile</h2>
  <p>Welcome, {{  user.username }}!</p>
  <p>Email: {{ user.email }}</p>
  <a href="{% url 'change_password' %}">Change Password</a>
{% endblock %}

catalog/templates/catalog/register.html
{% extends "base_generic.html" %}

{% block content %}
  <h2>Register</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
  </form>
  <p>Already have an account? <a href="{% url 'login' %}">Login here</a></p>
{% endblock %}